#ifndef GAMESTATE_H
#define GAMESTATE_H

typedef enum{
    //MAIN MENU
    GAME_STATE_MAIN_MENU,
    GAME_STATE_PLAY_GAME_MENU,          
    GAME_STATE_NEW_CONTINUE_NON_CUSTOM,  
    GAME_STATE_NEW_CONTINUE_CUSTOM,
    GAME_STATE_STUDIO_MENU,   
    GAME_STATE_ABOUT,    
    GAME_STATE_PLAY_GAME,
    GAME_STATE_CREATE_MENU,
    GAME_STATE_EDIT_MENU,
    GAME_STATE_DELETE_MENU,
    GAME_STATE_CREATE_SLOT_1,
    GAME_STATE_CREATE_SLOT_2,
    GAME_STATE_CREATE_SLOT_3,
    GAME_STATE_EDIT_SLOT_1,
    GAME_STATE_EDIT_SLOT_2,
    GAME_STATE_EDIT_SLOT_3,
    GAME_STATE_DELETE_SLOT_1,
    GAME_STATE_DELETE_SLOT_2,
    GAME_STATE_DELETE_SLOT_3,
    GAME_STATE_PLAY_CUSTOM_MENU,
    GAME_STATE_PLAY_CUSTOM_SLOT_1,
    GAME_STATE_PLAY_CUSTOM_SLOT_2,
    GAME_STATE_PLAY_CUSTOM_SLOT_3,
    GAME_STATE_CONTINUE_SLOT_1,
    GAME_STATE_CONTINUE_SLOT_2,
    GAME_STATE_CONTINUE_SLOT_3,
    GAME_STATE_MINI_GAME_STACK,
    GAME_STATE_PAUSE,
    GAME_STATE_PLAY_CUSTOM_STORY  // New state for playing custom stories
}GameState;



#endif
